### ISSUE TITLE
Custom Phantomjs version

### ISSUE THREAD

**Issue by vnen** [Medium/phantomjs#323]
Couldn't this module use a environment variable so the user can select which version they want to use? I see that's currently hard coded at https://github.com/Medium/phantomjs/blob/master/lib/phantomjs.js#L29.

It'd solve things like #288 and it'd allow users to use an older version too.

**Comment by nicks** [comment]
This has been discussed before; it causes a bunch more problems:
1) it breaks the hermetic-ness of package.json (i.e., what's in package.json doesn't match the code installed)
2) it breaks npm's assumptions about shared deps (i.e., package A and package B say they both depend on phantomjs 1.9.8, so npm lets them share dependencies, but package B actually requires 2.0.0 via a special env variable)
3) it actually won't work on most platforms because of the upstream phantomjs bugs (see #288)
Sorry, I wish there was a better solution, but I think we just need to fix phantomjs upstream.
