### ISSUE TITLE
phantom js is not working 

### ISSUE THREAD

**Issue by amitsingh0542** [Medium/phantomjs#354]
I tried to configure the Karma-phantomjs-launcher and it throws the error. I have seen same issue is facing with many people. Is there any work around with npm package for phantom js. I can not use manual veriosn to install phantomjs. Please help me to fix this issue.

![phantomjs error](https://cloud.githubusercontent.com/assets/5037180/8293630/674b2cf2-18fc-11e5-856a-b0122bcf5c0f.png)

**Comment by martinblaha** [comment]
Same here. Any idea how to fix that?
Thank you.

```
Phantom installation failed { [Error: EACCES, open '/var/www/veranstalter/node_modules/phantomjs/lib/phantom']
  errno: -13,
  code: 'EACCES',
  path: '/var/www/veranstalter/node_modules/phantomjs/lib/phantom' } Error: EACCES, open '/var/www/veranstalter/node_modules/phantomjs/lib/phantom'
    at Error (native)
npm ERR! Linux 3.2.0-23-generic-pae
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "phantomjs"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.17 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.17 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/veranstalter/npm-debug.log
```

**Comment by nicks** [comment]
@amitsingh0542 This error means that your network is blocking the request to download phantomjs. You probably need to adjust your proxy settings. You can also put phantomjs on PATH if your network is fundamentally broken, see https://github.com/Medium/phantomjs#i-tried-everything-but-my-network-is-b0rked-what-do-i-do

@martinblaha EACCESS means that you do not have permission to write to that directory, either because you need to run some chmods or because you have an anti-virus blocker that blocks writes to that directory, see https://github.com/Medium/phantomjs#installation-fails-with-error-eperm-or-operation-not-permitted-or-permission-denied
