### ISSUE TITLE
Wrong binary?

### ISSUE THREAD

**Issue by MiroHibler** [Medium/phantomjs#384]
I'm having an issue with PhantomJS on Ubuntu 14.04.2 LTS (GNU/Linux 3.13.0-57-generic x86_64) throwing this error (used in [UnCSS](https://github.com/giakki/uncss) package):

```shell
<snip>/phridge/node_modules/phantomjs/lib/phantom/bin/phantomjs: Syntax error: Unterminated quoted string
```

When I try to invoke it manually from the same path, I get:

```shell
./phantomjs: cannot execute binary file: Exec format error
```

it seems that the included phantomjs package installs wrong binary for this architecture.

**Comment by nicks** [comment]
have you tried installing a binary manually and putting it on PATH?

**Comment by fg2it** [comment]
@MiroHibler  Check the result of `file` on that binary. It is likely that you end up with the 32 bit version. If that is the case, the problem is likely to come from https://github.com/Medium/phantomjs/blob/master/install.js#L105 and `process.arch` not being `x64`.
You can check that by inserting something like
```nodejs
console.log('Detected platform/arch : ', process.platform, process.arch)
```
just before line 104 in `node_modules/phantomjs/install.js`. If `platform` is linux and `arch` is something else than `x64` the current logic is to default on ia32 binary.
I see 2 workardounds here:
- you install globally, by yourself, `phantomjs`. That should work.
- or, you kill lines 105, and 107 to 116 (included) in `install.js`. Could work, but I don't know how the install is handled. These changes could be overwritten by the install process downloading the original version of this file.

**Comment by fg2it** [comment]
@nicks It is unlikely to fix the problem of MiroHibler but at least I expect to fix #376 so I submitted a PR to avoid this default on ia32.

**Comment by jaytaylor** [comment]
NB: I've found this error can happen if you rsync node_modules from OS-X to a Linux host.

The solution is easy:

`rm -rf node_modules && npm install`

;)

**Comment by fg2it** [comment]
@jaytaylor in this case, it is to be expected. `PhantomJS` binary depends on the plateform and you cannot expect a macosx binary to run on linux. So, since your rsync is a simple copy, of course, you end up with the wrong binary on your linux and a reinstall is likely (but only likely) to fix this.

**Comment by jaytaylor** [comment]
@fg2it Precisely; My intent is simply to leave a breadcrumb to help others who have made a similar mistake, google the error and land here.

Just edited my comment to be more clear.

Cheers,
Jay

**Comment by alexch** [comment]
This is throwing a little monkey wrench into my Vagrant-based workflow. I want to be able to run tests on both host MacOS and guest Linux, no matter what console I'm currently in. I wonder if there's a way to change the `phantomjs` binary into a shell script wrapper that checks the current OS and runs the appropriate binary...

**Comment by nicks** [comment]
@alexch NPM expects you to run `npm rebuild` when switching platforms, to rebuild any platform-specific dependencies, see https://github.com/Medium/phantomjs#cross-platform-repositories for more information

**Comment by alexch** [comment]
That's a cleaner workaround. Thanks @nicks !

**Comment by fungjj92** [comment]
+1 !
