### ISSUE TITLE
Installing phantomjs behind a corporate proxy without strict-ssl = false

### ISSUE THREAD

**Issue by andrewmichaelsmith** [Medium/phantomjs#477]
We have a MITM SSL proxy at work with root cert generated by our company.

For all other npm dependencies the following works:

```npm config -g set cafile=/path/to/cafile.crt```

However - for phantomjs we get a CERT_UNTRUSTED error. I have read the official docs which suggest setting strict-ssl=false. But I'd really rather not do that - it means I don't do any validation on the code and could in theory be installing anything.

Is there any way to get the phantomjs install.js to support the "cafile" setting that seems to work just fine for the npm.org dependencies?

(Thanks for the great project, by the way!)

**Comment by nicks** [comment]
hmmmm...weird...we have other users who are actively using cafile, so not sure why it wouldn't work for you?

**Comment by andrewmichaelsmith** [comment]
@nicks ah that's interesting, I'd assumed from your docs that it wasn't supported (because they say to switch strict-ssl=false). I assume your users are using strict-ssl=true?

We found that when setting cafile our normal npm installs would work but I noticed that phantomjs's install is a bit different so was assuming this was unsupported. I will have a bit more of a tinker and let you know.

**Comment by jgibson** [comment]
My colleague @theothermattm and I ran into the same issue last year and worked with the team to get it fixed: #296. It broke recently due to a refactoring of how the cafile is passed to the underlying request library. The commit in question is: 2620fb283439181cab0a99b89fdf4532455bc35d. This switched from passing the CA certificates to to the underlying library from a normal option to an agentOption.

This probably works if you're using a custom certificate without a proxy, but according to the the docs here: https://github.com/request/request#tlsssl-protocol it could break:
> Keep in mind that, although `agentOptions` allows for a slightly wider range of configurations, the recommended way is via `options` object directly, as using `agentOptions` or `https.globalAgent.options` would not be applied in the same way in proxied environments (as data travels through a TLS connection instead of an http/https agent).

Fortunately the fix is trivial; simply specify `options.ca = ca` in addition to `options.agentOptions = { ca: ca }`.

**Comment by andrewmichaelsmith** [comment]
Brilliant - thanks!
